SELECT DEPARTMENT_NAME FROM HR.departments WHERE DEPARTMENT_NAME LIKE '%ing';
 
 
SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY, (MAX_SALARY - MIN_SALARY) VARIANCE 
FROM HR.jobs 
WHERE JOB_TITLE LIKE '%President%' OR JOB_TITLE LIKE '%Manager%' 
ORDER BY VARIANCE DESC, JOB_TITLE DESC;


SET DEFINE ON

SELECT &&EMPLOYEE_ID EMPLOYEE_ID, FIRST_NAME,SALARY, SALARY* 12
AS "ANNUAL SALARY", &&TAX_RATE "TAX RATE",(&TAX_RATE *(SALARY * 12)) AS TAX
FROM HR.employees
WHERE EMPLOYEE_ID = &EMPLOYEE_ID;



